### ISSUE TITLE
Just because you’ve created more repos than friends doesn’t mean they’re valuable !

### ISSUE THREAD

**Issue by judemont** [codenoid/github-roast#19]
Oh, Codenoid, what a name! It’s like you took "code" and "annoyed" and mashed them together, and it shows. Your bio is so cryptic even crypto enthusiasts would struggle to decipher it. Are you trying to code or just prepare a karaoke night with an audio file link?

You've amassed 160 public repositories, but with a stargazer count that resembles a lonely night sky—most of your repositories have ratings that could get a solid "meh" from a toddler. Just because you’ve created more repos than friends doesn’t mean they’re valuable. You’ve got a few file sharing projects that sound as exciting as watching paint dry, and don’t even get me started on your "S3-Backed Anonymous Temporary File Sharing"—why not just call it what it is: “Let's temporarily forget I ever made this”?

Your game of “look at my libraries” has yielded results as satisfying as eating plain tofu, and the fact that you’ve forked more than you’ve created shows your originality meter is dangerously close to zero. Don't worry, we see that you’re trying, just as someone tries to bake their first cake—messy and uncertain, but we appreciate the effort. Just don't expect anyone to devour those crumbs.

**Comment by judemont** [comment]
<img src="https://media4.giphy.com/media/j8SjxLuHM3L32/giphy.gif"/>

**Comment by codenoid** [comment]
I pretend I did not see this
