### ISSUE TITLE
Please add an opt-out

### ISSUE THREAD

**Issue by Baa14453** [codenoid/github-roast#20]
:(

**Comment by mahmoud-moursy** [comment]
I think if you just had the LLM scan for a "Be Nice!" string inside the README it should refuse to roast. The phrase "be nice" should be easy enough to fit into a README without suspicion, right?

**Comment by Sam-programs** [comment]
> I think if you just had the LLM scan for a "Be Nice!" string inside the README it should refuse to roast. The phrase "be nice" should be easy enough to fit into a README without suspicion, right?

It could be hideable with markdown comments.
Syntax:
`<!--Comment-->`

**Comment by samiam2013** [comment]
This software shouldn't exist. It's a hateful, reductive, lazy use of LLMs. Of course they're mean as s*** they were trained _on the internet_, take a look around. 

Anything short of github OAUTH for this and confirming that the user asked for this horrible treatment isn't just a mistake, it's a breach of what should be the fundamental ethics around programming.

**Comment by samiam2013** [comment]
Anything short of requiring github OAUTH login for this and confirming that the user asked for this treatment isn't just a mistake, it's a breach of what should be the fundamental ethics around programming.

It probably breaks a ton of terms of service and end user license agreements. The author should consider the implications of leaving this on the wider internet to be abused.

**Comment by Sankie005** [comment]
> Anything short of requiring github OAUTH login for this and confirming that the user asked for this treatment isn't just a mistake, it's a breach of what should be the fundamental ethics around programming.
> 
> It probably breaks a ton of terms of service and end user license agreements. The author should consider the implications of leaving this on the wider internet to be abused.

I understand your position but this app is just a simple LLM wrapper, the underlying scraping and text generation technology is on OpenAi's side, you could achieve similar results by simply typing in a username on whatever LLM of choice that has access to the internet. I hope you can contribute to this project and we can work on building an effective opt out system. Though it should be noted nothing is stopping another developer or project from replicating the same thing just without the opt out feature. As users in this thread have suggested a <Be Nice!> string in a user's bio or project readme's might be one way to get LLMs to stop being harsh and it's a possibility worth investigating.

**Comment by codenoid** [comment]
#47 is created

**Comment by adlai** [comment]
> author should consider the implications of leaving this on the wider internet to be abused

dark patterns of copy writing
