### ISSUE TITLE
There is no such language named Indian

### ISSUE THREAD

**Issue by bauripalash** [codenoid/github-roast#23]
You mentioned `indian` as a language where you intended Hindi. 

Here, 
https://github.com/codenoid/github-roast/blob/14ee4b6c6fa23fd76133b19d44939d15310c90c3/src/routes/llama/%2Bserver.js#L108

And, here

https://github.com/codenoid/github-roast/blob/14ee4b6c6fa23fd76133b19d44939d15310c90c3/src/routes/%2Bpage.svelte#L16

There exists no such language. I think you meant Hindi, which is one of 22 official languages of India.

**Comment by codenoid** [comment]
Thank you Palash
