### ISSUE TITLE
Github Profile Compliment

### ISSUE THREAD

**Issue by HSGamer** [codenoid/github-roast#26]
Although it's less fun than a roast, how about making a page to compliment any Github profile?

**Comment by joachimhodana** [comment]
This project is indeed "roaster", so compliment functionality does not fit it. It would make more sense to create similiar one (possibly fork?) and name it github-compliment. You would just have to change prompts.

**Comment by w-m** [comment]
There's https://praise-me.fly.dev already (via https://news.ycombinator.com/item?id=41154560)

**Comment by HSGamer** [comment]
> There's [praise-me.fly.dev](https://praise-me.fly.dev) already (via [news.ycombinator.com/item?id=41154560](https://news.ycombinator.com/item?id=41154560))

I knew that people would come up with an opposite site for this. I didn't expect it to be so quick.
Great, I can close this issue now.

> This project is indeed "roaster", so compliment functionality does not fit it. It would make more sense to create similiar one (possibly fork?) and name it github-compliment. You would just have to change prompts.

FYI, this is just an idea for a different page. I didn't ask to add such a feature to this project.
