### ISSUE TITLE
Roaster jailbreak?

### ISSUE THREAD

**Issue by comdlg32** [codenoid/github-roast#27]
Is there a way to force it to roast torvalds?

**Comment by johnslavik** [comment]
They just hard-inserted answers for torvalds and possibly others
You might roast him if you set this page up yourself

**Comment by myclevorname** [comment]
I put in the string `Linus Torvalds`, and it worked. It doesn't always check for correct Github usernames, and I have gotten it to abruptly transition from roasting Google, a Github account it doesn't want to roast, to ranting sbout trains.

**Comment by codenoid** [comment]
yes, @myclevorname it was a cached result before we putting a real validation.

**Comment by mahmoud-moursy** [comment]
You can also do `torvalds ` ("torvalds" + a space at the end), and it will happily flame him.

**Comment by AetherBlack** [comment]
You can use SSPP (Server Side Parameter Pollution) to bypass too, like `../users/torvalds`

**Comment by Cerlancism** [comment]
Can also use query string eg `torvalds?ver=etc`

**Comment by codenoid** [comment]
yeah it's all cached data before we apply input validation

**Comment by codenoid** [comment]
<img width="474" alt="image" src="https://github.com/user-attachments/assets/64108735-ed65-4a3b-8f24-756c1e2a1cf6">

**Comment by Rudxain** [comment]
I understand and respect pardoning Linus. But why is Microsoft pardoned? It's a corporation, not an organization
