### ISSUE TITLE
Update Info somehow incase the Github users change their profiles

### ISSUE THREAD

**Issue by Pekotaker** [codenoid/github-roast#36]
Is there an update info function anywhere? I think that this program stores roasts in some DB and uses the cached roasts once they are generated. 

I scan through the repo but can't seem to find it.

**Comment by codenoid** [comment]
I'm afraid I couldn't do that as OpenAI fund currently running on minimum-to-none, but yeah, If either OpenAI or GitHub want to support this project, I could make it happen

<img width="183" alt="image" src="https://github.com/user-attachments/assets/8222c6fa-64fa-44a2-8fbd-943160ce5b21">
