### ISSUE TITLE
roasting not working currently

### ISSUE THREAD

**Issue by sharkpog** [codenoid/github-roast#45]
today, i felt like putting random names in and seeing if the bot roasts them. turns out, it keeps giving me the error message. 
![Screenshot 2024-08-21 2 44 41 PM](https://github.com/user-attachments/assets/7320b4f8-0b7d-4d5f-a6a5-91e2a108b5ff)

**Comment by codenoid** [comment]
yeah man, I'm running out of OpenAI credits
