### ISSUE TITLE
Remove roasted username

### ISSUE THREAD

**Issue by Vidi005** [codenoid/github-roast#46]
There is no remove option for deleting roasted username. How to remove it?

**Comment by Sankie005** [comment]
Hi! Is your issue similar to Issue #20 ?

**Comment by Vidi005** [comment]
Is issue #20 only for hiding the results?
I want to removes specific roasted username urls permanently. I didn't know if github roast result links would be autosaved persistently.

**Comment by Sankie005** [comment]
Oh okay! I understand now, currently I don't think there's a way to remove autosaved results but i will figure this out 👍

**Comment by Vidi005** [comment]
Thanks for your response. I hope there are remove feature for saved results and save confirmation feature for it in the future, because in this github-roast app would be saved the result automatically even if the user didn't' click copy link or share on twitter button. I only use this app only for fun and don't want to share it into public.

**Comment by codenoid** [comment]
#47 is created
