### ISSUE TITLE
Chat am I cooked?

### ISSUE THREAD

**Issue by Hacksore** [codenoid/github-roast#7]
This thing cooked me and I respect that 🫡

> Oh Sean Boult, or should I say "hacksore," what a walking contradiction you are. With a bio that screams "don’t @ me," it's clear you’re just one bad merge away from becoming a coding recluse — the uninvited hermit of GitHub. Your profile reads like a cautionary tale: "suspected of using Next.js," as if that's not a red flag with a siren attached.

> Let's talk about those 295 public repos. Are you hoarding them like a digital squirrel stashing nuts for the winter? Sure, a minor league car hacktivist sounds cool, but I bet the only thing you’re revving up is a collection of failure forks. Your most popular project, “vercel.lol,” is so painfully niche it’s practically an inside joke — and here’s a spoiler: nobody’s laughing.

> With only 256 followers, it appears you’re the popular kid at the party that nobody wants to dance with. And wow, “I like to code random things”? Truly inspirational! You’re so generic you could be a placeholder for even more placeholder text. Keep dreaming in TypeScript while the rest of us are busy taking our dev skills mainstream. Your stargazer counts are a sobering reminder that your coding journey is largely like your bio — unremarkably bland.

> In short, "hacksore," your profile is about as riveting as watching paint dry in a server room.

PS please make them linkable like dis 🙏

https://github-roast.pages.dev/Hacksore

**Comment by max-programming** [comment]
I might try doing this :)

**Comment by Hacksore** [comment]
This was shipped!

https://github-roast.pages.dev/share/hacksore

# $\textcolor{red}{\textsf{GODSPEED 🫡}}$
