### ISSUE TITLE
Won't roast certain Github accounts.

### ISSUE THREAD

**Issue by myclevorname** [codenoid/github-roast#9]
If I input something like `torvalds` or `google`, the bot outputs "I'm good. I don't wanna roast USERNAME". I would like to make the bot roast Linus Torvalds himself.

**Comment by Edu4rdSHL** [comment]
Honestly, it's common sense, you can't roast Torvalds, that's it. :p

**Comment by myclevorname** [comment]
> Honestly, it's common sense, you can't roast Torvalds, that's it. :p

Yes it can.
![Screenshot_20240804-223338_Firefox](https://github.com/user-attachments/assets/57981721-fc6a-416b-a571-4241f90a3eb9)

EDIT: It claims the Github profile is empty, only because it can't get information about the user "@Linus Torvalds"

**Comment by Edu4rdSHL** [comment]
That's fake

**Comment by myclevorname** [comment]
Type in the string "Linus Torvalds"

**Comment by Edu4rdSHL** [comment]
I mean, the "Linux Torvalds" username doesn't exists, so...

**Comment by myclevorname** [comment]
It used to work until a recent commit changed the behavior. Some of the previous responses are still cached.
